image/urls.py
from django.conf.urls import patterns, include, url

from image import views
urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^formulario/$', views.formulario, name='formulario'),
	url(r'^thanks/$', views.thanks, name='thanks'),
	url(r'^formulario2/$', views.formulario2, name='formulario2'),
	url(r'^formulario3/$', views.formulario3, name='formulario3'),
)

library/urls.py
from django.conf.urls import patterns, include, url

from library import views
urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^formulario_readbook/$', views.formulario_readbook, name='formulario_readbook'),
	url(r'^get_genre_books/$', views.get_genre_books, name='get_genre_books'),
)

testy/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	url(r'^image/', include('image.urls', namespace='image')),
	url(r'^library/', include('library.urls', namespace='library')),
    # Examples:
    # url(r'^$', 'testy.views.home', name='home'),
    # url(r'^testy/', include('testy.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

image/models.py
from django.db import models
import os
from testy.settings import MEDIA_ROOT
from django.core.files.storage import FileSystemStorage
# Create your models here.

class Images(models.Model):
	nombre = models.CharField(max_length=30)
	imagen = models.ImageField(upload_to='image/img')

fs = FileSystemStorage(location=os.path.join(MEDIA_ROOT,'image/static'))
class Pics(models.Model):
	nombre = models.CharField(max_length=30)
	imagen = models.ImageField(upload_to='image/img',storage=fs)

fisy = FileSystemStorage(location=os.path.join(MEDIA_ROOT,'image/media'),base_url='/media/')
class Photos(models.Model):
	nombre = models.CharField(max_length=30)
	imagen = models.ImageField(upload_to='img',storage=fisy)

class Booly(models.Model):
	bol = models.BooleanField()

class Inty(models.Model):
	inty = models.IntegerField()

library/models.py
from django.db import models

class Genre(models.Model):
	name = models.CharField(max_length=30)

	def __unicode__(self):
		return self.name


class Author(models.Model):
	name = models.CharField(max_length=30)
	genre = models.ForeignKey(Genre)

class Book(models.Model):
	title = models.CharField(max_length=30)
	genre = models.ManyToManyField(Genre)
	author = models.ForeignKey(Author)

	def __unicode__(self):
		return self.title

class ReadBook(models.Model):
	genre = models.ForeignKey(Genre)
	books = models.ManyToManyField(Book)

image/forms.py
from django.forms import ModelForm
from image.models import Images, Pics, Photos

class ImageForm(ModelForm):
	class Meta:
		model = Images

class PicForm(ModelForm):
	class Meta:
		model = Pics

class PhotoForm(ModelForm):
	class Meta:
		model = Photos

library/forms.py
from django.forms import ModelForm
from library.models import ReadBook

class ReadBookForm(ModelForm):
	class Meta:
		model = ReadBook

image/views.py
#!/usr/bin/env python
# -*- coding: latin-1 -*-
# Create your views here.

from django.shortcuts import render
from django.http import HttpResponseRedirect

from image.models import Images, Pics, Photos
from image.forms import ImageForm, PicForm, PhotoForm

def index(request):
	imgs = Images.objects.all()
	pics = Pics.objects.all()
	photos = Photos.objects.all()
	return render(request, 'image/index.html',{'imgs':imgs,'pics':pics,'photos':photos})

def formulario(request):
	#print "oaaa" <-- this save me ... ¬¬
	#ue=False "usuario_existe":ue,
	if request.method == 'POST': # If the form has been submitted...
		form = ImageForm(request.POST, request.FILES) # A form bound to the POST data
		if form.is_valid(): # All validation rules pass
			
			nombre = form.cleaned_data['nombre']
			imagen = form.cleaned_data['imagen']
			i = Images(nombre=nombre,imagen=imagen)
			i.save()
			
			return HttpResponseRedirect('/image/thanks/')
			
	else:
		form = ImageForm()
	return render(request, 'image/form.html', {
		'form': form,
	})
def formulario2(request):
	#print "oaaa" <-- this save me ... ¬¬
	#ue=False "usuario_existe":ue,
	if request.method == 'POST': # If the form has been submitted...
		form = PicForm(request.POST, request.FILES) # A form bound to the POST data
		if form.is_valid(): # All validation rules pass
			
			nombre = form.cleaned_data['nombre']
			imagen = form.cleaned_data['imagen']
			p = Pics(nombre=nombre,imagen=imagen)
			p.save()
			
			return HttpResponseRedirect('/image/thanks/')
			
	else:
		form = PicForm()
	return render(request, 'image/form.html', {
		'form': form,
	})

def formulario3(request):
	#print "oaaa" <-- this save me ... ¬¬
	#ue=False "usuario_existe":ue,
	if request.method == 'POST': # If the form has been submitted...
		form = PhotoForm(request.POST, request.FILES) # A form bound to the POST data
		if form.is_valid(): # All validation rules pass
			
			nombre = form.cleaned_data['nombre']
			imagen = form.cleaned_data['imagen']
			p = Photos(nombre=nombre,imagen=imagen)
			p.save()
			
			return HttpResponseRedirect('/image/thanks/')
			
	else:
		form = PhotoForm()
	return render(request, 'image/form.html', {
		'form': form,
	})

def thanks(request):
	return render(request, 'image/thanks.html')

library/views.py
#!/usr/bin/env python
# -*- coding: latin-1 -*-
# Create your views here.

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse



from library.models import Book, Genre, ReadBook
from library.forms import ReadBookForm

def index(request):
	b = Book.objects.all()
	g = Genre.objects.all()
	r = ReadBook.objects.all()
	return render(request, 'library/index.html',{'books':b,'genres':g,'readbooks':r})

def formulario_readbook(request):
	#print "oaaa" <-- this save me ... ¬¬
	#ue=False "usuario_existe":ue,
	if request.method == 'POST': # If the form has been submitted...
		form = ReadBookForm(request.POST) # A form bound to the POST data
		if form.is_valid(): # All validation rules pass
			
			genre = form.cleaned_data['genre']
			books = form.cleaned_data['books']
			r = ReadBook(genre=genre,books=books)
			r.save()
			
			return HttpResponseRedirect('/library/thanks/')
		else:
			render(request, 'library/form.html', {
					'form': form,
					})
	else:
		form = ReadBookForm()
	return render(request, 'library/form.html', {
		'form': form,
	})

def get_genre_books(request):
	#genre = get_object_or_404(pk=request.GET.get('genre', None))
	# here render a template or something that shouls be multiple selector of the books)
	#resp = ", ".join(genre.book_set.values_list('title', flat=True))
	genre = request.GET.get('genre', None)
	resp = genre #"oliwi"
	return HttpResponse(resp)

image/templates/image/form.html
<form enctype="multipart/form-data" action="." method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

image/templates/image/index.html
{% load staticfiles %}
<img src="/media/img/perro.jpg" />
<ul>
{% for pho in photos %}

<li>{{ pho.nombre }} </li>
<li><img src="/media/media/{{ pho.imagen.name }}" alt="{{ pho.imagen.name }}" /> </li>
<li><img src="{{ pho.imagen.path }}" alt="{{ pho.imagen.path }}" /> </li>
<li><img src="{{ pho.imagen.url }}" alt="{{ pho.imagen.url }}" /> </li>

{% empty %}
<p> No hay photos que mostrar </p>
{% endfor %}
</ul>

<p>Hola soy el index de Image app </p>

<ul>
{% for p in pics %}

<li>{{ p.nombre }} </li>
<li><img src="{{ STATIC_URL }}{{ p.imagen.name }}" alt="{{ p.imagen.name }}" /> </li>
<li><img src="{{ p.imagen.path }}" alt="{{ p.imagen.path }}" /> </li>
<li><img src="{{ p.imagen.url }}" alt="{{ p.imagen.url }}" /> </li>

{% empty %}
<p> No hay pics que mostrar </p>
{% endfor %}
</ul>

<IMG SRC="/media/lentes.jpeg" ALT="probando media">
<ul>
{% for i in imgs %}

<li>{{ i.nombre }} </li>
<li><img src="{{ STATIC_URL }}{{ i.imagen.name }}" alt="{{ i.imagen.name }}" /> </li>
<li><img src="{{ i.imagen.path }}" alt="{{ i.imagen.path }}" /> </li>
<li><img src="{{ i.imagen.url }}" alt="{{ i.imagen.url }}" /> </li>

{% empty %}
<p> No hay imagens a mostrar </p>
{% endfor %}
</ul>

<IMG SRC="{% static 'image/img/lentes.jpeg' %}" ALT="probando">
<IMG SRC="/static/image/img/lentes.jpeg" ALT="probando2">
<IMG SRC="{{ STATIC_URL }}image/img/lentes.jpeg" ALT="probando3">

image/templates/image/thanks.html
<p>Imagen Agregada con exito...</p>

library/templates/library/form.html
<script src="{{STATIC_URL}}library/js/jquery-1.9.1.js"></script>
<script>
$(document).ready(function(){
$('#id_genre').change(function(){
	var oli = $('#id_genre:last-child')
    $('#books').load('{% url 'library:get_genre_books' %}'+"?genre="+oli);
});
});
</script>
<form action="" method="post">{% csrf_token %}

{{ form.genre }}
<div id="books"></div>
<input type="submit" value="Submit" disabled="yes" />

</form>

<br/>

{% url 'library:get_genre_books' %}

library/templates/library/index.html
<ld>
{% for b in books %}
<li>{{ b.title }}</li>
<li>Genre:<br/>
{% for g in b.genre.all %}
<ul>{{ g.name }}</ul>
{% endfor %}
</li>
<li>{{ b.author.name }}</li>
<br/>
{% empty %}
<li>No hay Libros</li>
{% endfor %}
</ld>